# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
          echo `REACT_APP_DOG_IMAGE_URL=${{ secrets.DOG_IMAGE_URL }}` >> .env
          echo `REACT_APP_CAT_FACT_URL=${{ secrets.CAT_FACT_URL}}` >> .env
          echo `REACT_APP_FOOTBALL_API_BASE_URL=${{ secrets.FOOTBALL_API_BASE_URL}}` >> .env
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
